// Package orchestrator provides core domain types, constants, and interfaces
// for the Crawbl backend orchestrator. This package defines the data structures
// used for authentication, user management, workspace management, messaging,
// and runtime status tracking.
//
// The orchestrator sits between the Flutter mobile app and each user's agent runtime
// swarm, handling routing, auth, orchestration, integrations, billing controls,
// and auditability.
package orchestrator

import (
	"errors"
	"strings"
	"time"

	"github.com/Crawbl-AI/crawbl-backend/migrations/orchestrator/seed"
)

// Default configuration constants for the orchestrator.
const (
	// DefaultWorkspaceName is the default name assigned to new workspaces.
	DefaultWorkspaceName = "My Swarm"

	// DefaultSwarmTitle is the default title for new swarm instances.
	DefaultSwarmTitle = "My Swarm"

	// DefaultAgentAvatarURL is the default avatar URL for agents (empty means no default).
	DefaultAgentAvatarURL = ""

	// UserSenderDisplayName is the display name used for user-sent messages in previews.
	UserSenderDisplayName = "You"
)

// Error variables define the sentinel errors used throughout the orchestrator package.
var (
	// ErrInvalidToken indicates the provided authentication token is malformed or invalid.
	ErrInvalidToken = errors.New("invalid token")

	// ErrUnauthorized indicates the request lacks valid authentication credentials.
	ErrUnauthorized = errors.New("unauthorized")

	// ErrUserNotFound indicates the requested user does not exist in the system.
	ErrUserNotFound = errors.New("user not found")

	// ErrUserDeleted indicates the user account has been deleted.
	ErrUserDeleted = errors.New("user deleted")

	// ErrNilPrincipal indicates a nil principal was provided where one is required.
	ErrNilPrincipal = errors.New("principal is required")

	// ErrEmptySubject indicates the principal subject field is empty.
	ErrEmptySubject = errors.New("principal subject is required")

	// ErrEmptyEmail indicates the principal email field is empty.
	ErrEmptyEmail = errors.New("principal email is required")

	// ErrNilUser indicates a nil user was provided where one is required.
	ErrNilUser = errors.New("user is required")
)

// AgentStatus represents the operational status of an agent within a workspace.
type AgentStatus string

// Agent status constants define the possible states an agent can be in.
const (
	// AgentStatusOnline indicates the agent is available and ready to handle requests.
	AgentStatusOnline AgentStatus = "online"

	// AgentStatusReading indicates the agent is evaluating the message (routing phase).
	AgentStatusReading AgentStatus = "reading"

	// AgentStatusThinking indicates the agent is generating a response (LLM inference).
	AgentStatusThinking AgentStatus = "thinking"

	// AgentStatusPending indicates the agent's runtime is provisioning or starting up.
	AgentStatusPending AgentStatus = "pending"

	// AgentStatusError indicates the agent encountered an error during processing.
	AgentStatusError AgentStatus = "error"

	// AgentStatusOffline indicates the agent is not available.
	AgentStatusOffline AgentStatus = "offline"

	// AgentStatusWriting indicates the agent is actively streaming a response (first token received).
	AgentStatusWriting AgentStatus = "writing"
)

// ConversationType represents the type of conversation in a workspace.
type ConversationType string

// Conversation type constants define the available conversation modes.
const (
	// ConversationTypeSwarm indicates a conversation with the entire swarm.
	ConversationTypeSwarm ConversationType = "swarm"

	// ConversationTypeAgent indicates a conversation with a single agent.
	ConversationTypeAgent ConversationType = "agent"
)

// MessageRole represents the sender role in a conversation message.
type MessageRole string

// Message role constants define who sent a particular message.
const (
	// MessageRoleUser indicates the message was sent by a human user.
	MessageRoleUser MessageRole = "user"

	// MessageRoleAgent indicates the message was sent by an AI agent.
	MessageRoleAgent MessageRole = "agent"

	// MessageRoleSystem indicates the message was generated by the system.
	MessageRoleSystem MessageRole = "system"
)

// MessageStatus represents the delivery status of a message.
type MessageStatus string

// Message status constants define the possible delivery states.
const (
	// MessageStatusPending indicates the message is being processed.
	MessageStatusPending MessageStatus = "pending"

	// MessageStatusDelivered indicates the message was successfully delivered.
	MessageStatusDelivered MessageStatus = "delivered"

	// MessageStatusFailed indicates the message failed to deliver.
	MessageStatusFailed MessageStatus = "failed"

	// MessageStatusSent indicates the message was accepted by the server but not yet delivered to an agent.
	MessageStatusSent MessageStatus = "sent"

	// MessageStatusRead indicates the message was read and is being processed by an agent.
	MessageStatusRead MessageStatus = "read"

	// MessageStatusIncomplete indicates the agent's response was interrupted (partial text received).
	MessageStatusIncomplete MessageStatus = "incomplete"

	// MessageStatusSilent indicates the agent consciously had nothing to say.
	MessageStatusSilent MessageStatus = "silent"

	// MessageStatusDelegated indicates the Manager routed the request to
	// a sub-agent. The message text contains the Manager's reasoning;
	// the mobile app renders it as a delegation card (dimmed/collapsible).
	MessageStatusDelegated MessageStatus = "delegated"
)

// MessageContentType represents the type of content in a message.
type MessageContentType string

// Message content type constants define the available content formats.
const (
	// MessageContentTypeText indicates plain text content.
	MessageContentTypeText MessageContentType = "text"

	// MessageContentTypeActionCard indicates interactive action card content.
	MessageContentTypeActionCard MessageContentType = "action_card"

	// MessageContentTypeToolStatus indicates tool execution status content.
	MessageContentTypeToolStatus MessageContentType = "tool_status"

	// MessageContentTypeSystem indicates system-generated content.
	MessageContentTypeSystem MessageContentType = "system"

	// MessageContentTypeLoading indicates a loading/placeholder state.
	MessageContentTypeLoading MessageContentType = "loading"

	// MessageContentTypeDelegation renders an agent-to-agent delegation
	// card in the mobile chat. Emitted inline when the Manager (or
	// any agent) hands a task off to a sub-agent via the streaming
	// pipeline or the send_message_to_agent MCP tool.
	// See BACKEND_REQUIREMENTS.md §11.
	MessageContentTypeDelegation MessageContentType = "delegation"

	// MessageContentTypeArtifact renders a versioned artifact card
	// (document, plan, spreadsheet, code file) inline in the
	// conversation. Artifacts persist beyond the chat history and
	// are versioned. See BACKEND_REQUIREMENTS.md §12.
	MessageContentTypeArtifact MessageContentType = "artifact"

	// MessageContentTypeWorkflow renders a multi-step workflow
	// progress card inline in the conversation. Shows the workflow
	// name, current step, and overall status. See
	// BACKEND_REQUIREMENTS.md §13.
	MessageContentTypeWorkflow MessageContentType = "workflow"

	// MessageContentTypeQuestions renders a multi-turn interactive question card.
	// Emitted by the ask_questions MCP tool.
	MessageContentTypeQuestions MessageContentType = "questions"
)

// ActionStyle represents the visual style of an action button.
type ActionStyle string

// String implements fmt.Stringer so ActionStyle logs as its string value.
func (s ActionStyle) String() string { return string(s) }

// Action style constants define the visual presentation of action items.
const (
	// ActionStylePrimary indicates a primary/prominent action style.
	ActionStylePrimary ActionStyle = "primary"

	// ActionStyleSecondary indicates a secondary/less prominent action style.
	ActionStyleSecondary ActionStyle = "secondary"

	// ActionStyleDestructive indicates a destructive/danger action style.
	ActionStyleDestructive ActionStyle = "destructive"
)

// ToolState represents the execution state of a tool.
type ToolState string

// String implements fmt.Stringer so ToolState logs as its string value.
func (s ToolState) String() string { return string(s) }

// Tool state constants define the possible execution states.
const (
	// ToolStateRunning indicates the tool is currently executing.
	ToolStateRunning ToolState = "running"

	// ToolStateCompleted indicates the tool finished successfully.
	ToolStateCompleted ToolState = "completed"

	// ToolStateFailed indicates the tool execution failed.
	ToolStateFailed ToolState = "failed"
)

// AttachmentType represents the type of file attachment.
type AttachmentType string

// Attachment type constants define the supported attachment formats.
const (
	// AttachmentTypeImage indicates an image file attachment.
	AttachmentTypeImage AttachmentType = "image"

	// AttachmentTypeVideo indicates a video file attachment.
	AttachmentTypeVideo AttachmentType = "video"

	// AttachmentTypeAudio indicates an audio file attachment.
	AttachmentTypeAudio AttachmentType = "audio"

	// AttachmentTypeFile indicates a generic file attachment.
	AttachmentTypeFile AttachmentType = "file"
)

// Principal represents an authenticated identity extracted from a bearer token.
// It contains the minimal information needed to identify a user in the system.
type Principal struct {
	// Subject is the unique identifier for the user (e.g., from the OAuth provider).
	Subject string

	// Email is the user's email address.
	Email string

	// Name is the user's display name (optional).
	Name string
}

// UserPreferences stores user-configurable settings and preferences.
type UserPreferences struct {
	// PlatformTheme is the user's preferred UI theme preference.
	PlatformTheme *string

	// PlatformLanguage is the user's preferred language code.
	PlatformLanguage *string

	// CurrencyCode is the user's preferred currency for billing (ISO 4217).
	CurrencyCode *string
}

// UserSubscription represents a user's subscription plan and status.
type UserSubscription struct {
	// Name is the display name of the subscription plan.
	Name string

	// Code is the unique identifier for the subscription plan.
	Code string

	// ExpiresAt is the timestamp when the subscription expires (nil for non-expiring).
	ExpiresAt *time.Time
}

// User represents a complete user record in the system.
// This is the primary entity for user data storage and retrieval.
type User struct {
	// ID is the internal unique identifier for the user.
	ID string

	// Subject is the external identity provider's unique identifier.
	Subject string

	// Email is the user's primary email address.
	Email string

	// Nickname is the user's chosen display name.
	Nickname string

	// Name is the user's given name.
	Name string

	// Surname is the user's family name.
	Surname string

	// AvatarURL is the URL to the user's profile picture.
	AvatarURL *string

	// CountryCode is the user's country (ISO 3166-1 alpha-2).
	CountryCode *string

	// DateOfBirth is the user's birth date.
	DateOfBirth *time.Time

	// CreatedAt is the timestamp when the user account was created.
	CreatedAt time.Time

	// UpdatedAt is the timestamp when the user record was last modified.
	UpdatedAt time.Time

	// DeletedAt is the soft-delete timestamp (nil if not deleted).
	DeletedAt *time.Time

	// IsBanned indicates whether the user account is banned.
	IsBanned bool

	// HasAgreedWithTerms indicates whether the user accepted terms of service.
	HasAgreedWithTerms bool

	// HasAgreedWithPrivacyPolicy indicates whether the user accepted the privacy policy.
	HasAgreedWithPrivacyPolicy bool

	// Preferences contains user-configurable settings.
	Preferences UserPreferences

	// Subscription contains the user's current subscription information.
	Subscription UserSubscription
}

// LegalDocuments contains the current legal document versions and content.
// Used for displaying terms of service and privacy policy to users.
type LegalDocuments struct {
	// TermsOfService is the full text of the terms of service.
	TermsOfService string

	// PrivacyPolicy is the full text of the privacy policy.
	PrivacyPolicy string

	// TermsOfServiceVersion is the version identifier for the current terms.
	TermsOfServiceVersion string

	// PrivacyPolicyVersion is the version identifier for the current privacy policy.
	PrivacyPolicyVersion string
}

// Workspace represents a user's workspace containing their swarm and conversations.
// Each user typically has one primary workspace that contains their AI swarm.
type Workspace struct {
	// ID is the unique identifier for the workspace.
	ID string

	// UserID is the owner's user ID.
	UserID string

	// Name is the display name of the workspace.
	Name string

	// CreatedAt is the timestamp when the workspace was created.
	CreatedAt time.Time

	// UpdatedAt is the timestamp when the workspace was last modified.
	UpdatedAt time.Time

	// Runtime contains the current status of the workspace's swarm runtime.
	Runtime *RuntimeStatus
}

// WorkspaceSummary contains aggregate information about a workspace,
// including agent count and the most recent message preview.
type WorkspaceSummary struct {
	// TotalAgents is the number of agents in the workspace.
	TotalAgents int

	// LastMessagePreview is the most recent message across all conversations.
	LastMessagePreview *LastMessagePreview
}

// LastMessagePreview represents a preview of the most recent message in a workspace.
type LastMessagePreview struct {
	// Text is the message text content.
	Text string

	// SenderName is the display name of the message sender.
	SenderName string

	// Timestamp is when the message was created.
	Timestamp time.Time
}

// RuntimeState represents the operational state of a user's swarm runtime.
type RuntimeState string

// Runtime state constants define the possible states of a swarm deployment.
const (
	// RuntimeStateProvisioning indicates the runtime is being created or updated.
	RuntimeStateProvisioning RuntimeState = "provisioning"

	// RuntimeStateReady indicates the runtime is fully operational and verified.
	RuntimeStateReady RuntimeState = "ready"

	// RuntimeStateOffline indicates the runtime is not running.
	RuntimeStateOffline RuntimeState = "offline"

	// RuntimeStateFailed indicates the runtime encountered an error.
	RuntimeStateFailed RuntimeState = "failed"
)

// AgentRole constants define the swarm hierarchy roles.
const (
	// AgentRoleSubAgent is a delegate agent under the Manager.
	AgentRoleSubAgent = "sub-agent"

	// AgentRoleManager is the swarm orchestrator (base agent, defined by SOUL.md).
	// Stored in the database. Does not get a per-agent conversation.
	AgentRoleManager = "manager"
)

// Agent represents an AI agent within a workspace swarm.
// Each workspace can have multiple agents with different roles.
type Agent struct {
	// ID is the unique identifier for the agent.
	ID string `json:"id"`

	// WorkspaceID is the workspace this agent belongs to.
	WorkspaceID string `json:"workspace_id"`

	// Name is the display name of the agent.
	Name string `json:"name"`

	// Role describes the agent's role in the swarm hierarchy (e.g., "sub-agent", "manager").
	Role string `json:"role"`

	// Slug is the agent runtime routing identifier for this agent.
	// Matches the [agents.<slug>] key in config.toml and is sent as agent_id in the webhook.
	Slug string `json:"slug"`

	// AvatarURL is the URL to the agent's avatar image.
	AvatarURL string `json:"avatar"`

	// Status indicates the current operational status of the agent.
	// Emitted with omitempty so an unset status serialises as no field
	// at all (not "") — mobile's AgentStatus enum parse would otherwise
	// reject an empty string on incoming socket events.
	Status AgentStatus `json:"status,omitempty"`

	// SystemPrompt is the LLM system message for this agent's personality.
	SystemPrompt string `json:"system_prompt,omitempty"`

	// Description is a short human-readable summary of the agent's purpose.
	Description string `json:"description"`

	// CreatedAt is the timestamp when the agent was created.
	CreatedAt time.Time `json:"created_at"`

	// UpdatedAt is the timestamp when the agent was last modified.
	UpdatedAt time.Time `json:"updated_at"`
}

// AgentTool represents a tool with full metadata from the tools DB table.
type AgentTool struct {
	Name        string
	DisplayName string
	Description string
	Category    AgentToolCategory
	IconURL     string
}

// AgentToolCategory groups tools by function for display.
type AgentToolCategory struct {
	ID       string
	Name     string
	ImageURL string
}

// AgentModelDef describes an available LLM model.
type AgentModelDef struct {
	ID          string
	Name        string
	Description string
}

// DefaultAgentModel is the model ID assigned to new agents.
// "auto" means the platform selects the best model (currently gpt-5-mini, future: AWS Bedrock routing).
const DefaultAgentModel = "auto"

// ResponseLength represents the response verbosity preference.
type ResponseLength string

// String implements fmt.Stringer so ResponseLength logs as its string value.
func (s ResponseLength) String() string { return string(s) }

const (
	// ResponseLengthAuto lets the model choose an appropriate response length.
	ResponseLengthAuto ResponseLength = "auto"

	// ResponseLengthShort requests a concise response.
	ResponseLengthShort ResponseLength = "short"

	// ResponseLengthMedium requests a moderately detailed response.
	ResponseLengthMedium ResponseLength = "medium"

	// ResponseLengthLong requests a thorough, detailed response.
	ResponseLengthLong ResponseLength = "long"
)

// AgentDetails is the full agent profile with stats.
// Tools are served separately via GET /v1/agents/{id}/tools.
type AgentDetails struct {
	Agent
	Description string
	SortOrder   int
	Stats       AgentStats
}

// AgentStats contains aggregate metrics for an agent.
type AgentStats struct {
	TotalMessages         int
	TotalTokensUsed       int64
	TotalPromptTokens     int64
	TotalCompletionTokens int64
	TotalRequests         int
}

// AgentSettings contains the agent's model configuration and prompts.
type AgentSettings struct {
	Model          AgentModelDef
	ResponseLength ResponseLength
	Prompts        []AgentPrompt
	// AllowedTools is the list of tool name strings this agent is
	// permitted to invoke. Sourced from agent_settings.allowed_tools
	// in Postgres (text[] column). An empty slice means the
	// agent has no explicit whitelist and the runtime falls back to
	// each agent's hardcoded default toolset (e.g. Wally's web_fetch
	// + web_search_tool pair). The crawbl-agent-runtime blueprint
	// endpoint forwards this field so runtime pods can enforce the
	// whitelist at tool-call time without a second round-trip.
	AllowedTools []string
}

// AgentPrompt represents a customizable agent prompt file.
type AgentPrompt struct {
	ID          string
	Name        string
	Description string
	Content     string
}

// AgentHistoryItem represents a conversation summary for an agent.
type AgentHistoryItem struct {
	ConversationID string
	Title          string
	Subtitle       string
	CreatedAt      *time.Time
}

// OffsetPagination contains offset-based pagination metadata.
type OffsetPagination struct {
	Total   int
	Limit   int
	Offset  int
	HasNext bool
}

// ToolPage represents a paginated list of tools.
type ToolPage struct {
	Data       []AgentTool
	Pagination OffsetPagination
}

// Conversation represents a chat conversation between a user and agents.
// Conversations can be with a single agent or the entire swarm.
type Conversation struct {
	// ID is the unique identifier for the conversation.
	ID string `json:"id"`

	// WorkspaceID is the workspace this conversation belongs to.
	WorkspaceID string `json:"workspace_id"`

	// AgentID is the agent ID for single-agent conversations (nil for swarm conversations).
	AgentID *string `json:"-"`

	// Type indicates whether this is a swarm or single-agent conversation.
	Type ConversationType `json:"type"`

	// Title is the display title of the conversation.
	Title string `json:"title"`

	// CreatedAt is the timestamp when the conversation was created.
	CreatedAt time.Time `json:"created_at"`

	// UpdatedAt is the timestamp when the conversation was last modified.
	UpdatedAt time.Time `json:"updated_at"`

	// UnreadCount is the number of unread messages for the current user.
	UnreadCount int `json:"unread_count"`

	// Agent is the associated agent for single-agent conversations.
	Agent *Agent `json:"agent,omitempty"`

	// LastMessage is the most recent message in the conversation.
	LastMessage *Message `json:"last_message,omitempty"`
}

// Message represents a single message within a conversation.
// Messages can be from users, agents, or the system.
type Message struct {
	// ID is the unique identifier for the message.
	ID string `json:"id"`

	// ConversationID is the conversation this message belongs to.
	ConversationID string `json:"conversation_id"`

	// Role indicates who sent the message.
	Role MessageRole `json:"role"`

	// Content contains the message body and metadata.
	Content MessageContent `json:"content"`

	// Status indicates the delivery status of the message.
	Status MessageStatus `json:"status"`

	// CreatedAt is the timestamp when the message was created.
	CreatedAt time.Time `json:"created_at"`

	// UpdatedAt is the timestamp when the message was last modified.
	UpdatedAt time.Time `json:"updated_at"`

	// LocalID is a client-generated ID for optimistic updates.
	LocalID *string `json:"local_id,omitempty"`

	// AgentID is the agent ID for agent messages.
	AgentID *string `json:"-"`

	// Agent is the agent that sent this message (for agent messages).
	Agent *Agent `json:"agent,omitempty"`

	// Attachments are files attached to this message.
	Attachments []Attachment `json:"attachments"`
}

// MessageContent represents the body of a message with type-specific data.
type MessageContent struct {
	// Type indicates the content format.
	Type MessageContentType `json:"type"`

	// Text is the text content for text messages.
	Text string `json:"text,omitempty"`

	// Title is the heading for structured content types.
	Title string `json:"title,omitempty"`

	// Description is additional context for structured content types.
	Description string `json:"description,omitempty"`

	// Actions are interactive buttons for action card content.
	Actions []ActionItem `json:"actions,omitempty"`

	// SelectedActionID is the ID of the user-selected action.
	SelectedActionID *string `json:"selected_action_id,omitempty"`

	// Tool status fields (type = "tool_status").
	Tool  string         `json:"tool,omitempty"`
	State ToolState      `json:"state,omitempty"`
	Query string         `json:"query,omitempty"`
	Args  map[string]any `json:"args,omitempty"`

	// Delegation fields (type = "delegation").
	From        *ContentAgent `json:"from,omitempty"`
	To          *ContentAgent `json:"to,omitempty"`
	Status      string        `json:"status,omitempty"`
	TaskPreview string        `json:"task_preview,omitempty"`

	// Questions fields (type = "questions").
	Turns   []QuestionTurn   `json:"turns,omitempty"`
	Answers []QuestionAnswer `json:"answers,omitempty"`

	// Artifact fields (type = "artifact"). Title and Status reuse the
	// existing MessageContent-level fields. Kept flat (not nested under
	// an artifact ref) because the mobile Freezed union decoder reads
	// them at the top level of the content object.
	ArtifactID     string `json:"artifact_id,omitempty"`
	Version        int    `json:"version,omitempty"`
	AgentSlug      string `json:"agent_slug,omitempty"`
	AgentName      string `json:"agent_name,omitempty"`
	ContentPreview string `json:"content_preview,omitempty"`

	// Workflow fields (type = "workflow"). Status reuses the
	// MessageContent-level Status field; name lives on WorkflowName
	// because Title is already used for artifact/questions.
	WorkflowID   string `json:"workflow_id,omitempty"`
	WorkflowName string `json:"workflow_name,omitempty"`
	ExecutionID  string `json:"execution_id,omitempty"`
}

// ContentAgent is the agent summary embedded in delegation and workflow
// message content. Matches the shape the mobile already uses for agent
// objects in message bubbles (id, name, role, slug, avatar, status).
type ContentAgent struct {
	ID     string      `json:"id"`
	Name   string      `json:"name"`
	Role   string      `json:"role"`
	Slug   string      `json:"slug"`
	Avatar string      `json:"avatar"`
	Status AgentStatus `json:"status,omitempty"`
}

// ContentAgentFromAgent converts an Agent to a ContentAgent summary.
func ContentAgentFromAgent(a *Agent) *ContentAgent {
	if a == nil {
		return nil
	}
	return &ContentAgent{
		ID:     a.ID,
		Name:   a.Name,
		Role:   a.Role,
		Slug:   a.Slug,
		Avatar: a.AvatarURL,
		Status: a.Status,
	}
}

// ActionItem represents an interactive button in an action card message.
type ActionItem struct {
	// ID is the unique identifier for this action.
	ID string `json:"id"`

	// Label is the display text for the action button.
	Label string `json:"label"`

	// Style determines the visual presentation of the action.
	Style ActionStyle `json:"style"`
}

// QuestionMode is the selection mode for a question item.
type QuestionMode string

const (
	// QuestionModeSingle allows at most one selected option plus optional custom text.
	QuestionModeSingle QuestionMode = "single"
	// QuestionModeMulti allows multiple selected options plus optional custom text.
	QuestionModeMulti QuestionMode = "multi"
)

// QuestionTurn groups related questions shown together as one turn block.
type QuestionTurn struct {
	// Index is the 1-based position of this turn in the message.
	Index int `json:"index"`
	// Label is an optional heading displayed above the turn.
	Label string `json:"label,omitempty"`
	// Questions are the question items belonging to this turn.
	Questions []QuestionItem `json:"questions"`
}

// QuestionItem is a single choice question inside a QuestionTurn.
type QuestionItem struct {
	// ID is the stable identifier for the question (e.g. "t1q2").
	ID string `json:"id"`
	// Prompt is the question text displayed to the user.
	Prompt string `json:"prompt"`
	// Mode controls whether the client allows single or multi selection.
	Mode QuestionMode `json:"mode"`
	// Options are the selectable answers.
	Options []QuestionOption `json:"options"`
	// AllowCustom indicates the client should render a free-text "write your own" slot.
	AllowCustom bool `json:"allow_custom"`
}

// QuestionOption is a selectable answer for a QuestionItem.
type QuestionOption struct {
	// ID is the option identifier within the question (e.g. "A", "B").
	ID string `json:"id"`
	// Label is the option text displayed to the user.
	Label string `json:"label"`
}

// QuestionAnswer captures a user's response to a QuestionItem.
type QuestionAnswer struct {
	// QuestionID identifies which question this answer belongs to.
	QuestionID string `json:"question_id"`
	// OptionIDs lists the selected option IDs. For QuestionModeSingle this must have at most one entry.
	OptionIDs []string `json:"option_ids,omitempty"`
	// CustomText holds a user-provided free-text answer when AllowCustom is true on the question.
	CustomText string `json:"custom_text,omitempty"`
}

// Attachment represents a file attached to a message.
type Attachment struct {
	// ID is the unique identifier for the attachment.
	ID string `json:"id"`

	// Name is the original filename of the attachment.
	Name string `json:"name"`

	// URL is the download URL for the attachment.
	URL string `json:"url"`

	// Type indicates the kind of attachment (image, video, audio, file).
	Type AttachmentType `json:"type"`

	// Size is the file size in bytes.
	Size int64 `json:"size"`

	// MIMEType is the MIME type of the file.
	MIMEType string `json:"mime_type,omitempty"`

	// Duration is the playback duration for audio/video in seconds.
	Duration *int `json:"duration,omitempty"`
}

// MessagePage represents a paginated list of messages.
type MessagePage struct {
	// Data is the slice of messages in this page.
	Data []*Message

	// Pagination contains the cursor-based pagination info.
	Pagination Pagination
}

// Pagination contains cursor-based pagination metadata.
type Pagination struct {
	// NextScrollID is the cursor for the next page.
	NextScrollID string

	// PrevScrollID is the cursor for the previous page.
	PrevScrollID string

	// HasNext indicates whether a next page exists.
	HasNext bool

	// HasPrev indicates whether a previous page exists.
	HasPrev bool
}

// RuntimeStatus represents the current state of a user's swarm runtime.
// This is populated from Kubernetes UserSwarm custom resource status,
// plus the identity fields (UserID, WorkspaceID) stamped by the runtime
// client so downstream gRPC calls can sign HMAC bearer tokens without
// a second lookup.
type RuntimeStatus struct {
	// SwarmName is the name of the swarm instance.
	SwarmName string

	// RuntimeNamespace is the Kubernetes namespace where the swarm runs.
	RuntimeNamespace string

	// ServiceName is the Kubernetes service name for the swarm.
	ServiceName string

	// UserID is the platform user ID that owns this workspace. Populated
	// by the runtime client on EnsureRuntime; used by downstream
	// SendText/Memory calls to sign HMAC bearer tokens for gRPC auth
	// against the per-workspace crawbl-agent-runtime pod.
	UserID string

	// WorkspaceID is the Crawbl workspace ID this runtime serves.
	// Populated alongside UserID so gRPC calls from the orchestrator to
	// the per-workspace pod can authenticate without a second lookup
	// into the workspaces table.
	WorkspaceID string

	// Phase is the current phase from the UserSwarm status.
	Phase string

	// Verified indicates whether the swarm has passed health verification.
	Verified bool

	// Status is the derived runtime state based on phase and verification.
	Status RuntimeState

	// LastError contains the most recent error message, if any.
	LastError string
}

// DefaultAgentBlueprint defines the configuration for a default agent in a new workspace.
type DefaultAgentBlueprint struct {
	// Name is the display name of the agent.
	Name string

	// Slug is the agent runtime routing identifier.
	Slug string

	// Role is the swarm hierarchy role.
	Role string

	// SystemPrompt is the LLM system message for this agent's personality.
	SystemPrompt string

	// Description is a short human-readable summary of the agent's purpose.
	Description string

	// AllowedTools is the list of tool name strings this agent is permitted to use.
	AllowedTools []string
}

// Mention represents an @-mention of an agent in a swarm message.
type Mention struct {
	AgentID   string `json:"agent_id"`
	AgentName string `json:"agent_name"`
	Offset    int    `json:"offset"`
	Length    int    `json:"length"`
}

// ItemType distinguishes tools from third-party integrations in the API response.
type ItemType string

const (
	// ItemTypeTool is an agent tool (search, memory, scheduling, etc.).
	ItemTypeTool ItemType = "tool"
	// ItemTypeApp is a third-party integration (Gmail, Slack, etc.).
	ItemTypeApp ItemType = "app"
)

// CategoryMeta holds display metadata for an item category.
// Used by the handler to build the categories list for GET /v1/integrations.
type CategoryMeta struct {
	ID       string
	Name     string
	ImageURL string
}

// APIVersion is the current API version string.
const APIVersion = "1.0.0"

// DefaultSubscriptionName is the display name for the default subscription plan.
const DefaultSubscriptionName = "Freemium"

// DefaultSubscriptionCode is the code identifier for the default subscription plan.
const DefaultSubscriptionCode = "freemium"

// GetDefaultAgents returns the list of default agent blueprints for new workspaces.
// Data is loaded from the embedded JSON seed files at compile time.
func GetDefaultAgents() []DefaultAgentBlueprint {
	entries := seed.DefaultAgents()
	out := make([]DefaultAgentBlueprint, len(entries))
	for i, e := range entries {
		out[i] = DefaultAgentBlueprint{
			Name:         e.Name,
			Slug:         e.Slug,
			Role:         e.Role,
			SystemPrompt: e.SystemPrompt,
			Description:  e.Description,
			AllowedTools: e.AllowedTools,
		}
	}
	return out
}

// GetAvailableModels returns the list of available LLM model definitions.
// Data is loaded from the embedded JSON seed files at compile time.
func GetAvailableModels() []AgentModelDef {
	entries := seed.AvailableModels()
	out := make([]AgentModelDef, len(entries))
	for i, e := range entries {
		out[i] = AgentModelDef{
			ID:          e.ID,
			Name:        e.Name,
			Description: e.Description,
		}
	}
	return out
}

// StatusForRuntime maps a runtime status to an agent status.
func StatusForRuntime(runtime *RuntimeStatus) AgentStatus {
	if runtime == nil {
		return AgentStatusOffline
	}
	if runtime.Verified {
		return AgentStatusOnline
	}
	switch strings.ToLower(strings.TrimSpace(runtime.Phase)) {
	case "progressing", "pending":
		return AgentStatusPending
	case "failed", "error":
		return AgentStatusError
	default:
		return AgentStatusOffline
	}
}

// EnrichAgentStatus sets each agent's status based on the workspace runtime state.
func EnrichAgentStatus(agents []*Agent, runtime *RuntimeStatus) {
	for _, agent := range agents {
		agent.Status = StatusForRuntime(runtime)
	}
}

// IntegrationCategories returns display metadata for integration (app) categories.
// Tool categories live in the agentruntime/tools package; these are merged at the handler level.
// Data is loaded from the embedded JSON seed files at compile time.
func IntegrationCategories() []CategoryMeta {
	entries := seed.IntegrationCategories()
	out := make([]CategoryMeta, len(entries))
	for i, e := range entries {
		out[i] = CategoryMeta{
			ID:       e.ID,
			Name:     e.Name,
			ImageURL: e.ImageURL,
		}
	}
	return out
}

// IntegrationItem represents an available integration with its connection status.
// Returned by GET /v1/integrations for the mobile app's Connected Apps screen.
type IntegrationItem struct {
	// Provider is the unique identifier for the integration (e.g., "google_calendar").
	Provider string
	// Name is the human-readable display name (e.g., "Google Calendar").
	Name string
	// Description explains what the integration does.
	Description string
	// IconURL is the URL to the integration's icon image.
	IconURL string
	// CategoryID groups the integration by type (e.g., "communication", "productivity").
	CategoryID string
	// IsConnected indicates whether the user has an active OAuth connection.
	IsConnected bool
	// IsEnabled indicates whether the integration is available for connection.
	// False means "coming soon" (shown but not connectable).
	IsEnabled bool
}

// OAuthConfig contains the OAuth parameters the mobile app needs to start
// an authorization flow via flutter_appauth.
type OAuthConfig struct {
	// ClientID is the OAuth client identifier for the provider.
	ClientID string
	// RedirectURL is the redirect URI registered with the provider.
	RedirectURL string
	// AuthorizationEndpoint is the provider's OAuth authorization URL.
	AuthorizationEndpoint string
	// TokenEndpoint is the provider's OAuth token exchange URL.
	TokenEndpoint string
	// Scopes is the list of OAuth scopes to request.
	Scopes []string
	// AdditionalParameters contains provider-specific OAuth parameters.
	AdditionalParameters map[string]string
}

// ResolveRuntimeState determines the runtime state based on Kubernetes phase
// and verification status. A verified swarm is always ready. Otherwise, the
// state is derived from the phase:
//   - Pending, Progressing, Deleting, or empty -> Provisioning
//   - Error -> Failed
//   - Suspended or unknown -> Offline
func ResolveRuntimeState(phase string, verified bool) RuntimeState {
	if verified {
		return RuntimeStateReady
	}

	switch phase {
	case "Pending", "Progressing", "Deleting", "":
		return RuntimeStateProvisioning
	case "Error":
		return RuntimeStateFailed
	case "Suspended":
		return RuntimeStateOffline
	default:
		return RuntimeStateOffline
	}
}
