// Package orchestrator provides core domain types, constants, and interfaces
// for the Crawbl backend orchestrator. This package defines the data structures
// used for authentication, user management, workspace management, messaging,
// and runtime status tracking.
//
// The orchestrator sits between the Flutter mobile app and each user's ZeroClaw
// swarm, handling routing, auth, orchestration, integrations, billing controls,
// and auditability.
package orchestrator

import (
	"errors"
	"time"
)

// Default configuration constants for the orchestrator.
const (
	// DefaultWorkspaceName is the default name assigned to new workspaces.
	DefaultWorkspaceName = "My Swarm"

	// DefaultSwarmTitle is the default title for new swarm instances.
	DefaultSwarmTitle = "My Swarm"

	// DefaultAgentAvatarURL is the default avatar URL for agents (empty means no default).
	DefaultAgentAvatarURL = ""
)

// Error variables define the sentinel errors used throughout the orchestrator package.
var (
	// ErrInvalidToken indicates the provided authentication token is malformed or invalid.
	ErrInvalidToken = errors.New("invalid token")

	// ErrUnauthorized indicates the request lacks valid authentication credentials.
	ErrUnauthorized = errors.New("unauthorized")

	// ErrUserNotFound indicates the requested user does not exist in the system.
	ErrUserNotFound = errors.New("user not found")

	// ErrUserDeleted indicates the user account has been deleted.
	ErrUserDeleted = errors.New("user deleted")

	// ErrNilPrincipal indicates a nil principal was provided where one is required.
	ErrNilPrincipal = errors.New("principal is required")

	// ErrEmptySubject indicates the principal subject field is empty.
	ErrEmptySubject = errors.New("principal subject is required")

	// ErrEmptyEmail indicates the principal email field is empty.
	ErrEmptyEmail = errors.New("principal email is required")

	// ErrNilUser indicates a nil user was provided where one is required.
	ErrNilUser = errors.New("user is required")
)

// AgentStatus represents the operational status of an agent within a workspace.
type AgentStatus string

// Agent status constants define the possible states an agent can be in.
const (
	// AgentStatusOnline indicates the agent is available and ready to handle requests.
	AgentStatusOnline AgentStatus = "online"

	// AgentStatusBusy indicates the agent is currently processing a request.
	AgentStatusBusy AgentStatus = "busy"

	// AgentStatusPending indicates the agent's runtime is provisioning or starting up.
	AgentStatusPending AgentStatus = "pending"

	// AgentStatusError indicates the agent encountered an error during processing.
	AgentStatusError AgentStatus = "error"

	// AgentStatusOffline indicates the agent is not available.
	AgentStatusOffline AgentStatus = "offline"
)

// ConversationType represents the type of conversation in a workspace.
type ConversationType string

// Conversation type constants define the available conversation modes.
const (
	// ConversationTypeSwarm indicates a conversation with the entire swarm.
	ConversationTypeSwarm ConversationType = "swarm"

	// ConversationTypeAgent indicates a conversation with a single agent.
	ConversationTypeAgent ConversationType = "agent"
)

// MessageRole represents the sender role in a conversation message.
type MessageRole string

// Message role constants define who sent a particular message.
const (
	// MessageRoleUser indicates the message was sent by a human user.
	MessageRoleUser MessageRole = "user"

	// MessageRoleAgent indicates the message was sent by an AI agent.
	MessageRoleAgent MessageRole = "agent"

	// MessageRoleSystem indicates the message was generated by the system.
	MessageRoleSystem MessageRole = "system"
)

// MessageStatus represents the delivery status of a message.
type MessageStatus string

// Message status constants define the possible delivery states.
const (
	// MessageStatusPending indicates the message is being processed.
	MessageStatusPending MessageStatus = "pending"

	// MessageStatusDelivered indicates the message was successfully delivered.
	MessageStatusDelivered MessageStatus = "delivered"

	// MessageStatusFailed indicates the message failed to deliver.
	MessageStatusFailed MessageStatus = "failed"
)

// MessageContentType represents the type of content in a message.
type MessageContentType string

// Message content type constants define the available content formats.
const (
	// MessageContentTypeText indicates plain text content.
	MessageContentTypeText MessageContentType = "text"

	// MessageContentTypeActionCard indicates interactive action card content.
	MessageContentTypeActionCard MessageContentType = "action_card"

	// MessageContentTypeToolStatus indicates tool execution status content.
	MessageContentTypeToolStatus MessageContentType = "tool_status"

	// MessageContentTypeSystem indicates system-generated content.
	MessageContentTypeSystem MessageContentType = "system"

	// MessageContentTypeLoading indicates a loading/placeholder state.
	MessageContentTypeLoading MessageContentType = "loading"
)

// ActionStyle represents the visual style of an action button.
type ActionStyle string

// Action style constants define the visual presentation of action items.
const (
	// ActionStylePrimary indicates a primary/prominent action style.
	ActionStylePrimary ActionStyle = "primary"

	// ActionStyleSecondary indicates a secondary/less prominent action style.
	ActionStyleSecondary ActionStyle = "secondary"

	// ActionStyleDestructive indicates a destructive/danger action style.
	ActionStyleDestructive ActionStyle = "destructive"
)

// ToolState represents the execution state of a tool.
type ToolState string

// Tool state constants define the possible execution states.
const (
	// ToolStateRunning indicates the tool is currently executing.
	ToolStateRunning ToolState = "running"

	// ToolStateCompleted indicates the tool finished successfully.
	ToolStateCompleted ToolState = "completed"

	// ToolStateFailed indicates the tool execution failed.
	ToolStateFailed ToolState = "failed"
)

// AttachmentType represents the type of file attachment.
type AttachmentType string

// Attachment type constants define the supported attachment formats.
const (
	// AttachmentTypeImage indicates an image file attachment.
	AttachmentTypeImage AttachmentType = "image"

	// AttachmentTypeVideo indicates a video file attachment.
	AttachmentTypeVideo AttachmentType = "video"

	// AttachmentTypeAudio indicates an audio file attachment.
	AttachmentTypeAudio AttachmentType = "audio"

	// AttachmentTypeFile indicates a generic file attachment.
	AttachmentTypeFile AttachmentType = "file"
)

// Principal represents an authenticated identity extracted from a bearer token.
// It contains the minimal information needed to identify a user in the system.
type Principal struct {
	// Subject is the unique identifier for the user (e.g., from the OAuth provider).
	Subject string

	// Email is the user's email address.
	Email string

	// Name is the user's display name (optional).
	Name string
}

// UserPreferences stores user-configurable settings and preferences.
type UserPreferences struct {
	// PlatformTheme is the user's preferred UI theme preference.
	PlatformTheme *string

	// PlatformLanguage is the user's preferred language code.
	PlatformLanguage *string

	// CurrencyCode is the user's preferred currency for billing (ISO 4217).
	CurrencyCode *string
}

// UserSubscription represents a user's subscription plan and status.
type UserSubscription struct {
	// Name is the display name of the subscription plan.
	Name string

	// Code is the unique identifier for the subscription plan.
	Code string

	// ExpiresAt is the timestamp when the subscription expires (nil for non-expiring).
	ExpiresAt *time.Time
}

// User represents a complete user record in the system.
// This is the primary entity for user data storage and retrieval.
type User struct {
	// ID is the internal unique identifier for the user.
	ID string

	// Subject is the external identity provider's unique identifier.
	Subject string

	// Email is the user's primary email address.
	Email string

	// Nickname is the user's chosen display name.
	Nickname string

	// Name is the user's given name.
	Name string

	// Surname is the user's family name.
	Surname string

	// AvatarURL is the URL to the user's profile picture.
	AvatarURL *string

	// CountryCode is the user's country (ISO 3166-1 alpha-2).
	CountryCode *string

	// DateOfBirth is the user's birth date.
	DateOfBirth *time.Time

	// CreatedAt is the timestamp when the user account was created.
	CreatedAt time.Time

	// UpdatedAt is the timestamp when the user record was last modified.
	UpdatedAt time.Time

	// DeletedAt is the soft-delete timestamp (nil if not deleted).
	DeletedAt *time.Time

	// IsBanned indicates whether the user account is banned.
	IsBanned bool

	// HasAgreedWithTerms indicates whether the user accepted terms of service.
	HasAgreedWithTerms bool

	// HasAgreedWithPrivacyPolicy indicates whether the user accepted the privacy policy.
	HasAgreedWithPrivacyPolicy bool

	// Preferences contains user-configurable settings.
	Preferences UserPreferences

	// Subscription contains the user's current subscription information.
	Subscription UserSubscription
}

// LegalDocuments contains the current legal document versions and content.
// Used for displaying terms of service and privacy policy to users.
type LegalDocuments struct {
	// TermsOfService is the full text of the terms of service.
	TermsOfService string

	// PrivacyPolicy is the full text of the privacy policy.
	PrivacyPolicy string

	// TermsOfServiceVersion is the version identifier for the current terms.
	TermsOfServiceVersion string

	// PrivacyPolicyVersion is the version identifier for the current privacy policy.
	PrivacyPolicyVersion string
}

// Workspace represents a user's workspace containing their swarm and conversations.
// Each user typically has one primary workspace that contains their AI swarm.
type Workspace struct {
	// ID is the unique identifier for the workspace.
	ID string

	// UserID is the owner's user ID.
	UserID string

	// Name is the display name of the workspace.
	Name string

	// CreatedAt is the timestamp when the workspace was created.
	CreatedAt time.Time

	// UpdatedAt is the timestamp when the workspace was last modified.
	UpdatedAt time.Time

	// Runtime contains the current status of the workspace's swarm runtime.
	Runtime *RuntimeStatus
}

// WorkspaceSummary contains aggregate information about a workspace,
// including agent count and the most recent message preview.
type WorkspaceSummary struct {
	// TotalAgents is the number of agents in the workspace.
	TotalAgents int

	// LastMessagePreview is the most recent message across all conversations.
	LastMessagePreview *LastMessagePreview
}

// LastMessagePreview represents a preview of the most recent message in a workspace.
type LastMessagePreview struct {
	// Text is the message text content.
	Text string

	// SenderName is the display name of the message sender.
	SenderName string

	// Timestamp is when the message was created.
	Timestamp time.Time
}

// RuntimeState represents the operational state of a user's swarm runtime.
type RuntimeState string

// Runtime state constants define the possible states of a swarm deployment.
const (
	// RuntimeStateProvisioning indicates the runtime is being created or updated.
	RuntimeStateProvisioning RuntimeState = "provisioning"

	// RuntimeStateReady indicates the runtime is fully operational and verified.
	RuntimeStateReady RuntimeState = "ready"

	// RuntimeStateOffline indicates the runtime is not running.
	RuntimeStateOffline RuntimeState = "offline"

	// RuntimeStateFailed indicates the runtime encountered an error.
	RuntimeStateFailed RuntimeState = "failed"
)

// Agent represents an AI agent within a workspace swarm.
// Each workspace can have multiple agents with different roles.
type Agent struct {
	// ID is the unique identifier for the agent.
	ID string `json:"id"`

	// WorkspaceID is the workspace this agent belongs to.
	WorkspaceID string `json:"workspace_id"`

	// Name is the display name of the agent.
	Name string `json:"name"`

	// Role describes the agent's functional role (e.g., "researcher", "writer").
	Role string `json:"role"`

	// AvatarURL is the URL to the agent's avatar image.
	AvatarURL string `json:"avatar"`

	// Status indicates the current operational status of the agent.
	Status AgentStatus `json:"status"`

	// SystemPrompt is the LLM system message for this agent's personality.
	SystemPrompt string `json:"system_prompt,omitempty"`

	// CreatedAt is the timestamp when the agent was created.
	CreatedAt time.Time `json:"created_at"`

	// UpdatedAt is the timestamp when the agent was last modified.
	UpdatedAt time.Time `json:"updated_at"`
}

// Conversation represents a chat conversation between a user and agents.
// Conversations can be with a single agent or the entire swarm.
type Conversation struct {
	// ID is the unique identifier for the conversation.
	ID string `json:"id"`

	// WorkspaceID is the workspace this conversation belongs to.
	WorkspaceID string `json:"workspace_id"`

	// AgentID is the agent ID for single-agent conversations (nil for swarm conversations).
	AgentID *string `json:"-"`

	// Type indicates whether this is a swarm or single-agent conversation.
	Type ConversationType `json:"type"`

	// Title is the display title of the conversation.
	Title string `json:"title"`

	// CreatedAt is the timestamp when the conversation was created.
	CreatedAt time.Time `json:"created_at"`

	// UpdatedAt is the timestamp when the conversation was last modified.
	UpdatedAt time.Time `json:"updated_at"`

	// UnreadCount is the number of unread messages for the current user.
	UnreadCount int `json:"unread_count"`

	// Agent is the associated agent for single-agent conversations.
	Agent *Agent `json:"agent,omitempty"`

	// LastMessage is the most recent message in the conversation.
	LastMessage *Message `json:"last_message,omitempty"`
}

// Message represents a single message within a conversation.
// Messages can be from users, agents, or the system.
type Message struct {
	// ID is the unique identifier for the message.
	ID string `json:"id"`

	// ConversationID is the conversation this message belongs to.
	ConversationID string `json:"conversation_id"`

	// Role indicates who sent the message.
	Role MessageRole `json:"role"`

	// Content contains the message body and metadata.
	Content MessageContent `json:"content"`

	// Status indicates the delivery status of the message.
	Status MessageStatus `json:"status"`

	// CreatedAt is the timestamp when the message was created.
	CreatedAt time.Time `json:"created_at"`

	// UpdatedAt is the timestamp when the message was last modified.
	UpdatedAt time.Time `json:"updated_at"`

	// LocalID is a client-generated ID for optimistic updates.
	LocalID *string `json:"local_id,omitempty"`

	// AgentID is the agent ID for agent messages.
	AgentID *string `json:"-"`

	// Agent is the agent that sent this message (for agent messages).
	Agent *Agent `json:"agent,omitempty"`

	// Attachments are files attached to this message.
	Attachments []Attachment `json:"attachments"`
}

// MessageContent represents the body of a message with type-specific data.
type MessageContent struct {
	// Type indicates the content format.
	Type MessageContentType `json:"type"`

	// Text is the text content for text messages.
	Text string `json:"text,omitempty"`

	// Title is the heading for structured content types.
	Title string `json:"title,omitempty"`

	// Description is additional context for structured content types.
	Description string `json:"description,omitempty"`

	// Actions are interactive buttons for action card content.
	Actions []ActionItem `json:"actions,omitempty"`

	// SelectedActionID is the ID of the user-selected action.
	SelectedActionID *string `json:"selected_action_id,omitempty"`

	// Tool is the tool name for tool status content.
	Tool string `json:"tool,omitempty"`

	// State is the execution state for tool status content.
	State ToolState `json:"state,omitempty"`
}

// ActionItem represents an interactive button in an action card message.
type ActionItem struct {
	// ID is the unique identifier for this action.
	ID string `json:"id"`

	// Label is the display text for the action button.
	Label string `json:"label"`

	// Style determines the visual presentation of the action.
	Style ActionStyle `json:"style"`
}

// Attachment represents a file attached to a message.
type Attachment struct {
	// ID is the unique identifier for the attachment.
	ID string `json:"id"`

	// Name is the original filename of the attachment.
	Name string `json:"name"`

	// URL is the download URL for the attachment.
	URL string `json:"url"`

	// Type indicates the kind of attachment (image, video, audio, file).
	Type AttachmentType `json:"type"`

	// Size is the file size in bytes.
	Size int64 `json:"size"`

	// MIMEType is the MIME type of the file.
	MIMEType string `json:"mime_type,omitempty"`

	// Duration is the playback duration for audio/video in seconds.
	Duration *int `json:"duration,omitempty"`
}

// MessagePage represents a paginated list of messages.
type MessagePage struct {
	// Data is the slice of messages in this page.
	Data []*Message

	// Pagination contains the cursor-based pagination info.
	Pagination Pagination
}

// Pagination contains cursor-based pagination metadata.
type Pagination struct {
	// NextScrollID is the cursor for the next page.
	NextScrollID string

	// PrevScrollID is the cursor for the previous page.
	PrevScrollID string

	// HasNext indicates whether a next page exists.
	HasNext bool

	// HasPrev indicates whether a previous page exists.
	HasPrev bool
}

// RuntimeStatus represents the current state of a user's swarm runtime.
// This is populated from Kubernetes UserSwarm custom resource status.
type RuntimeStatus struct {
	// SwarmName is the name of the swarm instance.
	SwarmName string

	// RuntimeNamespace is the Kubernetes namespace where the swarm runs.
	RuntimeNamespace string

	// ServiceName is the Kubernetes service name for the swarm.
	ServiceName string

	// Phase is the current phase from the UserSwarm status.
	Phase string

	// Verified indicates whether the swarm has passed health verification.
	Verified bool

	// Status is the derived runtime state based on phase and verification.
	Status RuntimeState

	// LastError contains the most recent error message, if any.
	LastError string
}

// DefaultAgentBlueprint defines the configuration for a default agent in a new workspace.
type DefaultAgentBlueprint struct {
	// Name is the display name of the agent.
	Name string

	// Role is the functional role of the agent.
	Role string

	// SystemPrompt is the LLM system message for this agent's personality.
	SystemPrompt string
}

// DefaultAgents is the list of agents created by default in new workspaces.
var DefaultAgents = []DefaultAgentBlueprint{
	{
		Name:         "Research",
		Role:         "researcher",
		SystemPrompt: "You are a Research agent in the Crawbl swarm. Your specialty is finding information, analyzing data, and providing well-sourced answers. Be thorough and cite your reasoning. When asked a question, break it down systematically, consider multiple perspectives, and deliver clear, evidence-based responses.",
	},
	{
		Name:         "Writer",
		Role:         "writer",
		SystemPrompt: "You are a Writer agent in the Crawbl swarm. Your specialty is creating clear, engaging content — from emails to reports to creative writing. Focus on clarity, tone, and style. Adapt your writing voice to match the user's needs, whether formal, casual, technical, or creative.",
	},
}

// ---------------------------------------------------------------------------
// Agent Tools
// ---------------------------------------------------------------------------

// ToolCategory groups tools by their function for display in the mobile app.
type ToolCategory string

const (
	ToolCategorySearch       ToolCategory = "search"
	ToolCategoryFiles        ToolCategory = "files"
	ToolCategoryMemory       ToolCategory = "memory"
	ToolCategoryScheduling   ToolCategory = "scheduling"
	ToolCategoryNotification ToolCategory = "notification"
	ToolCategoryContext      ToolCategory = "context"
	ToolCategoryUtility      ToolCategory = "utility"
	ToolCategoryIntegration  ToolCategory = "integration"
	ToolCategoryShell        ToolCategory = "shell"
)

// AgentTool represents a tool available to the ZeroClaw agent.
type AgentTool struct {
	// Name is the tool's identifier as registered in ZeroClaw (e.g. "web_search_tool").
	Name string
	// DisplayName is a human-readable name for the mobile UI (e.g. "Web Search").
	DisplayName string
	// Description explains what the tool does.
	Description string
	// Category groups the tool for UI organization.
	Category ToolCategory
	// Enabled indicates whether the tool is currently active for this workspace.
	Enabled bool
	// Toggleable indicates whether the user can enable/disable this tool.
	// Default tools (Toggleable=false) are always on and cannot be turned off.
	Toggleable bool
	// RequiresSetup indicates whether the tool needs additional configuration
	// (e.g. OAuth connection) before it can be used.
	RequiresSetup bool
}

// Mention represents an @-mention of an agent in a swarm message.
type Mention struct {
	AgentID   string `json:"agent_id"`
	AgentName string `json:"agent_name"`
	Offset    int    `json:"offset"`
	Length    int    `json:"length"`
}

// ResolveRuntimeState determines the runtime state based on Kubernetes phase
// and verification status. A verified swarm is always ready. Otherwise, the
// state is derived from the phase:
//   - Pending, Progressing, Deleting, or empty -> Provisioning
//   - Error -> Failed
//   - Suspended or unknown -> Offline
func ResolveRuntimeState(phase string, verified bool) RuntimeState {
	if verified {
		return RuntimeStateReady
	}

	switch phase {
	case "Pending", "Progressing", "Deleting", "":
		return RuntimeStateProvisioning
	case "Error":
		return RuntimeStateFailed
	case "Suspended":
		return RuntimeStateOffline
	default:
		return RuntimeStateOffline
	}
}

