// Memory service for the crawbl-agent-runtime.
//
// This service is the gRPC equivalent of the old /api/memory HTTP
// endpoint. It is a facade — the actual memories table lives in the
// orchestrator's Postgres database. The runtime calls this service locally
// for shape convenience; the runtime-side handler forwards the calls to the
// orchestrator over the same HMAC-authed MCP bridge used for other
// orchestrator-mediated tools.
//
// Plan reference:
//   .omc/plans/2026-04-05-crawbl-agent-runtime-plan.md §6.6 (state ownership)
//   .omc/plans/2026-04-05-crawbl-agent-runtime-plan.md §13 (Memory tier = Postgres)

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: agentruntime/v1/memory.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MemoryEntry is a single row from the memories table, surfaced to agents
// via the runtime's memory_recall tool and via direct Memory.ListMemories
// calls.
type MemoryEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Key is the stable identifier within a (workspace, category) namespace.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Content is the actual memory body. For content larger than 8 KB, the
	// orchestrator may store the body in DigitalOcean Spaces and return a
	// blob_key pointer here instead — Phase 2+ optimization, not Phase 1.
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Category partitions memories for UI grouping and for scoped recall.
	// Common values: "core", "daily", "conversation".
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryEntry) Reset() {
	*x = MemoryEntry{}
	mi := &file_agentruntime_v1_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryEntry) ProtoMessage() {}

func (x *MemoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_agentruntime_v1_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryEntry.ProtoReflect.Descriptor instead.
func (*MemoryEntry) Descriptor() ([]byte, []int) {
	return file_agentruntime_v1_memory_proto_rawDescGZIP(), []int{0}
}

func (x *MemoryEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *MemoryEntry) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryEntry) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MemoryEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *MemoryEntry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListMemoriesRequest struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// Category optionally filters by category. Empty = all categories.
	Category string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	// Limit caps the number of entries returned. 0 = server default (100).
	Limit int32 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// Offset is the number of entries to skip for pagination. 0 = start.
	Offset        int32 `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemoriesRequest) Reset() {
	*x = ListMemoriesRequest{}
	mi := &file_agentruntime_v1_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemoriesRequest) ProtoMessage() {}

func (x *ListMemoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentruntime_v1_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemoriesRequest.ProtoReflect.Descriptor instead.
func (*ListMemoriesRequest) Descriptor() ([]byte, []int) {
	return file_agentruntime_v1_memory_proto_rawDescGZIP(), []int{1}
}

func (x *ListMemoriesRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListMemoriesRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListMemoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMemoriesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListMemoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*MemoryEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemoriesResponse) Reset() {
	*x = ListMemoriesResponse{}
	mi := &file_agentruntime_v1_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemoriesResponse) ProtoMessage() {}

func (x *ListMemoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentruntime_v1_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemoriesResponse.ProtoReflect.Descriptor instead.
func (*ListMemoriesResponse) Descriptor() ([]byte, []int) {
	return file_agentruntime_v1_memory_proto_rawDescGZIP(), []int{2}
}

func (x *ListMemoriesResponse) GetEntries() []*MemoryEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type CreateMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemoryRequest) Reset() {
	*x = CreateMemoryRequest{}
	mi := &file_agentruntime_v1_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemoryRequest) ProtoMessage() {}

func (x *CreateMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentruntime_v1_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemoryRequest.ProtoReflect.Descriptor instead.
func (*CreateMemoryRequest) Descriptor() ([]byte, []int) {
	return file_agentruntime_v1_memory_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMemoryRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *CreateMemoryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CreateMemoryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateMemoryRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type CreateMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *MemoryEntry           `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMemoryResponse) Reset() {
	*x = CreateMemoryResponse{}
	mi := &file_agentruntime_v1_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMemoryResponse) ProtoMessage() {}

func (x *CreateMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentruntime_v1_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMemoryResponse.ProtoReflect.Descriptor instead.
func (*CreateMemoryResponse) Descriptor() ([]byte, []int) {
	return file_agentruntime_v1_memory_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMemoryResponse) GetEntry() *MemoryEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type DeleteMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoryRequest) Reset() {
	*x = DeleteMemoryRequest{}
	mi := &file_agentruntime_v1_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoryRequest) ProtoMessage() {}

func (x *DeleteMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agentruntime_v1_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemoryRequest) Descriptor() ([]byte, []int) {
	return file_agentruntime_v1_memory_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteMemoryRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *DeleteMemoryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoryResponse) Reset() {
	*x = DeleteMemoryResponse{}
	mi := &file_agentruntime_v1_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoryResponse) ProtoMessage() {}

func (x *DeleteMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agentruntime_v1_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteMemoryResponse) Descriptor() ([]byte, []int) {
	return file_agentruntime_v1_memory_proto_rawDescGZIP(), []int{6}
}

var File_agentruntime_v1_memory_proto protoreflect.FileDescriptor

const file_agentruntime_v1_memory_proto_rawDesc = "" +
	"\n" +
	"\x1cagentruntime/v1/memory.proto\x12\x16crawbl.agentruntime.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcb\x01\n" +
	"\vMemoryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x82\x01\n" +
	"\x13ListMemoriesRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"U\n" +
	"\x14ListMemoriesResponse\x12=\n" +
	"\aentries\x18\x01 \x03(\v2#.crawbl.agentruntime.v1.MemoryEntryR\aentries\"\x80\x01\n" +
	"\x13CreateMemoryRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"Q\n" +
	"\x14CreateMemoryResponse\x129\n" +
	"\x05entry\x18\x01 \x01(\v2#.crawbl.agentruntime.v1.MemoryEntryR\x05entry\"J\n" +
	"\x13DeleteMemoryRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\x16\n" +
	"\x14DeleteMemoryResponse2\xc9\x02\n" +
	"\x06Memory\x12i\n" +
	"\fListMemories\x12+.crawbl.agentruntime.v1.ListMemoriesRequest\x1a,.crawbl.agentruntime.v1.ListMemoriesResponse\x12i\n" +
	"\fCreateMemory\x12+.crawbl.agentruntime.v1.CreateMemoryRequest\x1a,.crawbl.agentruntime.v1.CreateMemoryResponse\x12i\n" +
	"\fDeleteMemory\x12+.crawbl.agentruntime.v1.DeleteMemoryRequest\x1a,.crawbl.agentruntime.v1.DeleteMemoryResponseBNZLgithub.com/Crawbl-AI/crawbl-backend/internal/agentruntime/proto/v1;runtimev1b\x06proto3"

var (
	file_agentruntime_v1_memory_proto_rawDescOnce sync.Once
	file_agentruntime_v1_memory_proto_rawDescData []byte
)

func file_agentruntime_v1_memory_proto_rawDescGZIP() []byte {
	file_agentruntime_v1_memory_proto_rawDescOnce.Do(func() {
		file_agentruntime_v1_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agentruntime_v1_memory_proto_rawDesc), len(file_agentruntime_v1_memory_proto_rawDesc)))
	})
	return file_agentruntime_v1_memory_proto_rawDescData
}

var file_agentruntime_v1_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_agentruntime_v1_memory_proto_goTypes = []any{
	(*MemoryEntry)(nil),           // 0: crawbl.agentruntime.v1.MemoryEntry
	(*ListMemoriesRequest)(nil),   // 1: crawbl.agentruntime.v1.ListMemoriesRequest
	(*ListMemoriesResponse)(nil),  // 2: crawbl.agentruntime.v1.ListMemoriesResponse
	(*CreateMemoryRequest)(nil),   // 3: crawbl.agentruntime.v1.CreateMemoryRequest
	(*CreateMemoryResponse)(nil),  // 4: crawbl.agentruntime.v1.CreateMemoryResponse
	(*DeleteMemoryRequest)(nil),   // 5: crawbl.agentruntime.v1.DeleteMemoryRequest
	(*DeleteMemoryResponse)(nil),  // 6: crawbl.agentruntime.v1.DeleteMemoryResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_agentruntime_v1_memory_proto_depIdxs = []int32{
	7, // 0: crawbl.agentruntime.v1.MemoryEntry.created_at:type_name -> google.protobuf.Timestamp
	7, // 1: crawbl.agentruntime.v1.MemoryEntry.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: crawbl.agentruntime.v1.ListMemoriesResponse.entries:type_name -> crawbl.agentruntime.v1.MemoryEntry
	0, // 3: crawbl.agentruntime.v1.CreateMemoryResponse.entry:type_name -> crawbl.agentruntime.v1.MemoryEntry
	1, // 4: crawbl.agentruntime.v1.Memory.ListMemories:input_type -> crawbl.agentruntime.v1.ListMemoriesRequest
	3, // 5: crawbl.agentruntime.v1.Memory.CreateMemory:input_type -> crawbl.agentruntime.v1.CreateMemoryRequest
	5, // 6: crawbl.agentruntime.v1.Memory.DeleteMemory:input_type -> crawbl.agentruntime.v1.DeleteMemoryRequest
	2, // 7: crawbl.agentruntime.v1.Memory.ListMemories:output_type -> crawbl.agentruntime.v1.ListMemoriesResponse
	4, // 8: crawbl.agentruntime.v1.Memory.CreateMemory:output_type -> crawbl.agentruntime.v1.CreateMemoryResponse
	6, // 9: crawbl.agentruntime.v1.Memory.DeleteMemory:output_type -> crawbl.agentruntime.v1.DeleteMemoryResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_agentruntime_v1_memory_proto_init() }
func file_agentruntime_v1_memory_proto_init() {
	if File_agentruntime_v1_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agentruntime_v1_memory_proto_rawDesc), len(file_agentruntime_v1_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agentruntime_v1_memory_proto_goTypes,
		DependencyIndexes: file_agentruntime_v1_memory_proto_depIdxs,
		MessageInfos:      file_agentruntime_v1_memory_proto_msgTypes,
	}.Build()
	File_agentruntime_v1_memory_proto = out.File
	file_agentruntime_v1_memory_proto_goTypes = nil
	file_agentruntime_v1_memory_proto_depIdxs = nil
}
