// Memory service for the crawbl-agent-runtime.
//
// This service is the gRPC equivalent of the old /api/memory HTTP
// endpoint. It is a facade — the actual memories table lives in the
// orchestrator's Postgres database. The runtime calls this service locally
// for shape convenience; the runtime-side handler forwards the calls to the
// orchestrator over the same HMAC-authed MCP bridge used for other
// orchestrator-mediated tools.
//
// Plan reference:
//   .omc/plans/2026-04-05-crawbl-agent-runtime-plan.md §6.6 (state ownership)
//   .omc/plans/2026-04-05-crawbl-agent-runtime-plan.md §13 (Memory tier = Postgres)

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: agentruntime/v1/memory.proto

package runtimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Memory_ListMemories_FullMethodName = "/crawbl.agentruntime.v1.Memory/ListMemories"
	Memory_CreateMemory_FullMethodName = "/crawbl.agentruntime.v1.Memory/CreateMemory"
	Memory_DeleteMemory_FullMethodName = "/crawbl.agentruntime.v1.Memory/DeleteMemory"
)

// MemoryClient is the client API for Memory service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Memory exposes CRUD operations on the workspace's memory entries.
// All methods require workspace_id and are authenticated via the same HMAC
// bearer token used for AgentRuntime.Converse.
type MemoryClient interface {
	ListMemories(ctx context.Context, in *ListMemoriesRequest, opts ...grpc.CallOption) (*ListMemoriesResponse, error)
	CreateMemory(ctx context.Context, in *CreateMemoryRequest, opts ...grpc.CallOption) (*CreateMemoryResponse, error)
	DeleteMemory(ctx context.Context, in *DeleteMemoryRequest, opts ...grpc.CallOption) (*DeleteMemoryResponse, error)
}

type memoryClient struct {
	cc grpc.ClientConnInterface
}

func NewMemoryClient(cc grpc.ClientConnInterface) MemoryClient {
	return &memoryClient{cc}
}

func (c *memoryClient) ListMemories(ctx context.Context, in *ListMemoriesRequest, opts ...grpc.CallOption) (*ListMemoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMemoriesResponse)
	err := c.cc.Invoke(ctx, Memory_ListMemories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryClient) CreateMemory(ctx context.Context, in *CreateMemoryRequest, opts ...grpc.CallOption) (*CreateMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMemoryResponse)
	err := c.cc.Invoke(ctx, Memory_CreateMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryClient) DeleteMemory(ctx context.Context, in *DeleteMemoryRequest, opts ...grpc.CallOption) (*DeleteMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMemoryResponse)
	err := c.cc.Invoke(ctx, Memory_DeleteMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemoryServer is the server API for Memory service.
// All implementations must embed UnimplementedMemoryServer
// for forward compatibility.
//
// Memory exposes CRUD operations on the workspace's memory entries.
// All methods require workspace_id and are authenticated via the same HMAC
// bearer token used for AgentRuntime.Converse.
type MemoryServer interface {
	ListMemories(context.Context, *ListMemoriesRequest) (*ListMemoriesResponse, error)
	CreateMemory(context.Context, *CreateMemoryRequest) (*CreateMemoryResponse, error)
	DeleteMemory(context.Context, *DeleteMemoryRequest) (*DeleteMemoryResponse, error)
	mustEmbedUnimplementedMemoryServer()
}

// UnimplementedMemoryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemoryServer struct{}

func (UnimplementedMemoryServer) ListMemories(context.Context, *ListMemoriesRequest) (*ListMemoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMemories not implemented")
}
func (UnimplementedMemoryServer) CreateMemory(context.Context, *CreateMemoryRequest) (*CreateMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMemory not implemented")
}
func (UnimplementedMemoryServer) DeleteMemory(context.Context, *DeleteMemoryRequest) (*DeleteMemoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMemory not implemented")
}
func (UnimplementedMemoryServer) mustEmbedUnimplementedMemoryServer() {}
func (UnimplementedMemoryServer) testEmbeddedByValue()                {}

// UnsafeMemoryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemoryServer will
// result in compilation errors.
type UnsafeMemoryServer interface {
	mustEmbedUnimplementedMemoryServer()
}

func RegisterMemoryServer(s grpc.ServiceRegistrar, srv MemoryServer) {
	// If the following call panics, it indicates UnimplementedMemoryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Memory_ServiceDesc, srv)
}

func _Memory_ListMemories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMemoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServer).ListMemories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Memory_ListMemories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServer).ListMemories(ctx, req.(*ListMemoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Memory_CreateMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServer).CreateMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Memory_CreateMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServer).CreateMemory(ctx, req.(*CreateMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Memory_DeleteMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServer).DeleteMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Memory_DeleteMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServer).DeleteMemory(ctx, req.(*DeleteMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Memory_ServiceDesc is the grpc.ServiceDesc for Memory service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Memory_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crawbl.agentruntime.v1.Memory",
	HandlerType: (*MemoryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMemories",
			Handler:    _Memory_ListMemories_Handler,
		},
		{
			MethodName: "CreateMemory",
			Handler:    _Memory_CreateMemory_Handler,
		},
		{
			MethodName: "DeleteMemory",
			Handler:    _Memory_DeleteMemory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agentruntime/v1/memory.proto",
}
