// Package crawbl.agentruntime.v1 is the wire contract between the Crawbl
// orchestrator and the crawbl-agent-runtime pod. Every agent conversation,
// tool call, and streaming event flows through this proto. It replaces the
// HTTP/NDJSON webhook format that the legacy Rust agent runtime used.
//
// Plan reference: .omc/plans/2026-04-05-crawbl-agent-runtime-plan.md §6.3.
//
// Wire rules:
//   - gRPC bidi stream on port 42618 inside each workspace pod.
//   - HMAC bearer token in the "authorization" gRPC metadata header.
//   - Session correlation via the typed session_id field, NOT a header.
//   - Streaming events are a oneof — servers MUST emit ChunkEvents / ToolCall /
//     ToolResult events before the final DoneEvent.
//   - No field renumbers. No field deletions without a reserved range. Proto
//     evolution rules apply from day 1 because this is a frozen contract
//     until a named Phase 5 lockstep upgrade plan exists.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: agentruntime/v1/runtime.proto

package runtimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentRuntime_Converse_FullMethodName = "/crawbl.agentruntime.v1.AgentRuntime/Converse"
)

// AgentRuntimeClient is the client API for AgentRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentRuntime is the per-workspace runtime service. Orchestrator clients
// open a Converse bidi stream, send ConverseRequest messages from the mobile
// user, and receive ConverseEvent oneofs back until a DoneEvent closes the
// turn.
type AgentRuntimeClient interface {
	// Converse is a bidi stream. The first ConverseRequest on the stream MUST
	// include workspace_id and user_id. Subsequent requests on the same stream
	// reuse those values and set message + optional agent_id + optional
	// system_prompt. The server responds with zero or more ChunkEvent /
	// ThinkingEvent / ToolCallEvent / ToolResultEvent events followed by
	// exactly one DoneEvent per input request.
	Converse(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConverseRequest, ConverseEvent], error)
}

type agentRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentRuntimeClient(cc grpc.ClientConnInterface) AgentRuntimeClient {
	return &agentRuntimeClient{cc}
}

func (c *agentRuntimeClient) Converse(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ConverseRequest, ConverseEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentRuntime_ServiceDesc.Streams[0], AgentRuntime_Converse_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ConverseRequest, ConverseEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntime_ConverseClient = grpc.BidiStreamingClient[ConverseRequest, ConverseEvent]

// AgentRuntimeServer is the server API for AgentRuntime service.
// All implementations must embed UnimplementedAgentRuntimeServer
// for forward compatibility.
//
// AgentRuntime is the per-workspace runtime service. Orchestrator clients
// open a Converse bidi stream, send ConverseRequest messages from the mobile
// user, and receive ConverseEvent oneofs back until a DoneEvent closes the
// turn.
type AgentRuntimeServer interface {
	// Converse is a bidi stream. The first ConverseRequest on the stream MUST
	// include workspace_id and user_id. Subsequent requests on the same stream
	// reuse those values and set message + optional agent_id + optional
	// system_prompt. The server responds with zero or more ChunkEvent /
	// ThinkingEvent / ToolCallEvent / ToolResultEvent events followed by
	// exactly one DoneEvent per input request.
	Converse(grpc.BidiStreamingServer[ConverseRequest, ConverseEvent]) error
	mustEmbedUnimplementedAgentRuntimeServer()
}

// UnimplementedAgentRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentRuntimeServer struct{}

func (UnimplementedAgentRuntimeServer) Converse(grpc.BidiStreamingServer[ConverseRequest, ConverseEvent]) error {
	return status.Error(codes.Unimplemented, "method Converse not implemented")
}
func (UnimplementedAgentRuntimeServer) mustEmbedUnimplementedAgentRuntimeServer() {}
func (UnimplementedAgentRuntimeServer) testEmbeddedByValue()                      {}

// UnsafeAgentRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentRuntimeServer will
// result in compilation errors.
type UnsafeAgentRuntimeServer interface {
	mustEmbedUnimplementedAgentRuntimeServer()
}

func RegisterAgentRuntimeServer(s grpc.ServiceRegistrar, srv AgentRuntimeServer) {
	// If the following call panics, it indicates UnimplementedAgentRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentRuntime_ServiceDesc, srv)
}

func _AgentRuntime_Converse_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentRuntimeServer).Converse(&grpc.GenericServerStream[ConverseRequest, ConverseEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntime_ConverseServer = grpc.BidiStreamingServer[ConverseRequest, ConverseEvent]

// AgentRuntime_ServiceDesc is the grpc.ServiceDesc for AgentRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "crawbl.agentruntime.v1.AgentRuntime",
	HandlerType: (*AgentRuntimeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Converse",
			Handler:       _AgentRuntime_Converse_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agentruntime/v1/runtime.proto",
}
