package zeroclaw

// This file implements the init container's config merge logic.
//
// Problem: The operator manages certain config keys (provider, model, gateway settings),
// but ZeroClaw also writes to the same config.toml at runtime (adding learned preferences,
// session state, etc.). We can't just overwrite the live config on every reconcile —
// that would destroy ZeroClaw's accumulated state.
//
// Solution: Selective merge. The init container reads both the bootstrap config (from the
// ConfigMap) and the live config (from the PVC), then copies only the operator-managed
// keys from bootstrap → live. Everything else in the live config is preserved.
//
// First boot: If no live config exists yet, the bootstrap config is written as-is.
//
// The merge also resolves the api_key from environment variables (the ConfigMap never
// contains the actual key — it comes from an ESO-managed Secret mounted as env vars).
//
// This file runs inside the init container via "crawbl platform bootstrap".
// It does NOT run in the webhook — the webhook only generates the ConfigMap content.

import (
	"bytes"
	"fmt"
	"os"

	"github.com/BurntSushi/toml"

	"github.com/Crawbl-AI/crawbl-backend/internal/pkg/configenv"
	"github.com/Crawbl-AI/crawbl-backend/internal/pkg/fileutil"
)

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

// EnsureManagedConfig is the init container's main function. It ensures the
// PVC-backed live config contains the latest operator-managed values.
//
// Steps:
//  1. Read the bootstrap config from the ConfigMap mount.
//  2. If no live config exists on the PVC → write bootstrap as-is (first boot).
//  3. If live config exists → merge only operator-managed keys from bootstrap into live.
//  4. Resolve the api_key from environment variables.
//  5. Write the merged config atomically (temp file + rename).
func EnsureManagedConfig(bootstrapPath, livePath string) error {
	// Step 1: Read the bootstrap config generated by the webhook.
	bootstrapBytes, err := os.ReadFile(bootstrapPath)
	if err != nil {
		return fmt.Errorf("read bootstrap config: %w", err)
	}

	// Step 2: First boot — no live config yet, just write bootstrap as-is.
	if _, err := os.Stat(livePath); os.IsNotExist(err) {
		return fileutil.WriteAtomically(livePath, bootstrapBytes, configFilePerm)
	} else if err != nil {
		return fmt.Errorf("stat live config: %w", err)
	}

	// Step 3: Merge operator-managed keys into the existing live config.
	bootstrapDoc, err := fileutil.DecodeTOML(bootstrapBytes)
	if err != nil {
		return fmt.Errorf("decode bootstrap config: %w", err)
	}

	liveBytes, err := os.ReadFile(livePath)
	if err != nil {
		return fmt.Errorf("read live config: %w", err)
	}
	liveDoc, err := fileutil.DecodeTOML(liveBytes)
	if err != nil {
		return fmt.Errorf("decode live config: %w", err)
	}

	mergeManaged(liveDoc, bootstrapDoc)

	// Step 4: Resolve api_key from environment variables.
	resolveAPIKey(liveDoc)

	// Step 5: Write the merged config atomically.
	var buf bytes.Buffer
	if err := toml.NewEncoder(&buf).Encode(liveDoc); err != nil {
		return fmt.Errorf("encode merged config: %w", err)
	}
	return fileutil.WriteAtomically(livePath, buf.Bytes(), configFilePerm)
}

// ---------------------------------------------------------------------------
// Merge logic
// ---------------------------------------------------------------------------

// mergeManaged copies operator-managed keys from bootstrap into live.
// Non-managed keys in live are preserved untouched.
//
// For root-level keys: copy directly.
// For section keys (e.g. "autonomy.level"): ensure the section exists in live,
// then copy individual keys within it.
func mergeManaged(live, bootstrap map[string]any) {
	for section, keys := range managedKeys {
		if section == "" {
			// Root-level keys.
			for _, key := range keys {
				if val, ok := bootstrap[key]; ok {
					live[key] = val
				}
			}
			continue
		}

		// Section-level keys.
		srcSection, ok := bootstrap[section].(map[string]any)
		if !ok {
			continue
		}

		dstSection, ok := live[section].(map[string]any)
		if !ok {
			dstSection = map[string]any{}
			live[section] = dstSection
		}

		for _, key := range keys {
			if val, ok := srcSection[key]; ok {
				dstSection[key] = val
			}
		}
	}
}

// resolveAPIKey sets the api_key in the config from environment variables.
// The ConfigMap never contains the actual key — it's injected via an
// ESO-managed Secret mounted as env vars on the init container.
func resolveAPIKey(doc map[string]any) {
	for _, envName := range apiKeyEnvVars {
		value := configenv.SecretString(envName, "")
		if value == "" {
			continue
		}
		fmt.Fprintf(os.Stderr, "Using API key from environment variable %s\n", envName)
		doc["api_key"] = value
		return
	}
}


