package zeroclaw

// This file implements the init container's config merge logic.
//
// Problem: The operator manages certain config keys (provider, model, gateway settings),
// but ZeroClaw also writes to the same config.toml at runtime (adding learned preferences,
// session state, etc.). We can't just overwrite the live config on every reconcile —
// that would destroy ZeroClaw's accumulated state.
//
// Solution: Selective merge. The init container reads both the bootstrap config (from the
// ConfigMap) and the live config (from the PVC), then copies only the operator-managed
// keys from bootstrap → live. Everything else in the live config is preserved.
//
// First boot: If no live config exists yet, the bootstrap config is written as-is.
//
// The merge also resolves the api_key from environment variables (the ConfigMap never
// contains the actual key — it comes from an ESO-managed Secret mounted as env vars).
//
// This file runs inside the init container via "crawbl platform bootstrap".
// It does NOT run in the webhook — the webhook only generates the ConfigMap content.

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"

	"github.com/BurntSushi/toml"

	"github.com/Crawbl-AI/crawbl-backend/internal/pkg/configenv"
	"github.com/Crawbl-AI/crawbl-backend/internal/pkg/fileutil"
)

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

// EnsureManagedConfig is the init container's main function. It ensures the
// PVC-backed live config contains the latest operator-managed values.
//
// Steps:
//  1. Read the bootstrap config from the ConfigMap mount.
//  2. If no live config exists on the PVC → write bootstrap as-is (first boot).
//  3. If live config exists → merge only operator-managed keys from bootstrap into live.
//  4. Resolve the api_key from environment variables.
//  5. Write the merged config atomically (temp file + rename).
func EnsureManagedConfig(bootstrapPath, livePath string) error {
	// Step 1: Read the bootstrap config generated by the webhook.
	bootstrapBytes, err := os.ReadFile(bootstrapPath)
	if err != nil {
		return fmt.Errorf("read bootstrap config: %w", err)
	}

	// Step 2: First boot — no live config yet, just write bootstrap as-is.
	if _, err := os.Stat(livePath); os.IsNotExist(err) {
		return fileutil.WriteAtomically(livePath, bootstrapBytes, configFilePerm)
	} else if err != nil {
		return fmt.Errorf("stat live config: %w", err)
	}

	// Step 3: Merge operator-managed keys into the existing live config.
	bootstrapDoc, err := fileutil.DecodeTOML(bootstrapBytes)
	if err != nil {
		return fmt.Errorf("decode bootstrap config: %w", err)
	}

	liveBytes, err := os.ReadFile(livePath)
	if err != nil {
		return fmt.Errorf("read live config: %w", err)
	}
	liveDoc, err := fileutil.DecodeTOML(liveBytes)
	if err != nil {
		return fmt.Errorf("decode live config: %w", err)
	}

	mergeManaged(liveDoc, bootstrapDoc)

	// Step 4: Resolve api_key from environment variables.
	resolveAPIKey(liveDoc)

	// Step 5: Write the merged config atomically.
	var buf bytes.Buffer
	if err := toml.NewEncoder(&buf).Encode(liveDoc); err != nil {
		return fmt.Errorf("encode merged config: %w", err)
	}
	return fileutil.WriteAtomically(livePath, buf.Bytes(), configFilePerm)
}

// ---------------------------------------------------------------------------
// Merge logic
// ---------------------------------------------------------------------------

// mergeManaged applies operator-managed values from bootstrap into live.
// Non-managed keys in live are preserved untouched (ZeroClaw-owned state).
func mergeManaged(live, bootstrap map[string]any) {
	for _, ms := range managedSections {
		switch ms.strategy {
		case replaceSection:
			replaceFullSection(live, bootstrap, ms.section)
		case mergeKeys:
			mergeSectionKeys(live, bootstrap, ms)
		}
	}
}

// replaceFullSection overwrites an entire TOML section from bootstrap.
// If bootstrap doesn't have the section, it's removed from live.
// Used for sections like "agents" where the operator defines the complete set.
func replaceFullSection(live, bootstrap map[string]any, section string) {
	if val, ok := bootstrap[section]; ok {
		live[section] = val
	} else {
		delete(live, section)
	}
}

// mergeSectionKeys copies individual operator-managed keys from bootstrap into live.
// Keys not in the managed list are left untouched in live.
// When section is empty, keys are treated as root-level TOML keys.
func mergeSectionKeys(live, bootstrap map[string]any, ms managedSection) {
	// Root-level keys (no section nesting).
	if ms.section == "" {
		for _, key := range ms.keys {
			if val, ok := bootstrap[key]; ok {
				live[key] = val
			}
		}
		return
	}

	// Nested section keys — ensure both source and destination exist.
	srcSection, ok := bootstrap[ms.section].(map[string]any)
	if !ok {
		return
	}
	dstSection, ok := live[ms.section].(map[string]any)
	if !ok {
		dstSection = map[string]any{}
		live[ms.section] = dstSection
	}

	for _, key := range ms.keys {
		if val, ok := srcSection[key]; ok {
			dstSection[key] = val
		}
	}
}

// resolveAPIKey sets the api_key in the config from environment variables.
// The ConfigMap never contains the actual key — it's injected via an
// ESO-managed Secret mounted as env vars on the init container.
func resolveAPIKey(doc map[string]any) {
	for _, envName := range apiKeyEnvVars {
		value := configenv.SecretString(envName, "")
		if value == "" {
			continue
		}
		fmt.Fprintf(os.Stderr, "Using API key from environment variable %s\n", envName)
		doc["api_key"] = value
		return
	}
}

// EnsureAgentSkills writes per-agent personality files to the PVC.
// Each agent gets a directory at {workspace}/agents/{name}/ containing
// markdown skill files that ZeroClaw loads via the skills_directory config.
//
// Files are overwritten on every boot (operator-managed content).
func EnsureAgentSkills(workspaceDir string, agentFiles map[string]map[string]string) error {
	for agentName, files := range agentFiles {
		if !isValidAgentName(agentName) {
			return fmt.Errorf("invalid agent name %q: must match [a-z0-9][a-z0-9_-]*", agentName)
		}
		agentDir := filepath.Join(workspaceDir, "agents", agentName)
		if err := os.MkdirAll(agentDir, 0o755); err != nil {
			return fmt.Errorf("create agent dir %s: %w", agentName, err)
		}
		for filename, content := range files {
			if !isValidFileName(filename) {
				return fmt.Errorf("invalid file name %q for agent %s", filename, agentName)
			}
			path := filepath.Join(agentDir, filename)
			if err := fileutil.WriteAtomically(path, []byte(content), 0o644); err != nil {
				return fmt.Errorf("write %s/%s: %w", agentName, filename, err)
			}
		}
	}
	return nil
}

// isValidAgentName checks that an agent name is a safe filesystem identifier.
// Prevents path traversal via names like "../../etc".
func isValidAgentName(name string) bool {
	if len(name) == 0 || len(name) > 63 {
		return false
	}
	for _, c := range name {
		if !((c >= 'a' && c <= 'z') || (c >= '0' && c <= '9') || c == '-' || c == '_') {
			return false
		}
	}
	return name[0] != '-' && name[0] != '_'
}

// isValidFileName checks that a file name contains no path separators or traversal.
func isValidFileName(name string) bool {
	if len(name) == 0 || len(name) > 255 {
		return false
	}
	for _, c := range name {
		if c == '/' || c == '\\' || c == 0 {
			return false
		}
	}
	return name != "." && name != ".."
}

