{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "orchestrator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "orchestrator.labels" . | indent 4 }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.imagePullSecrets }}
  - name: {{ .name }}
{{- end }}
{{- end }}
{{- end }}
