# TODO: UPDATE THIS EXAMPLE, IT USES OLD STYLE OF USERSWARM CRD
apiVersion: crawbl.ai/v1alpha1
kind: UserSwarm
metadata:
  name: demo-user
spec:
  userId: "demo-user"
  placement:
    runtimeNamespace: swarms-dev
  runtime:
    image: registry.digitalocean.com/crawbl/zeroclaw@v0.5.9
    mode: daemon
    port: 42617
    imagePullSecretName: crawbl-docr
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  storage:
    size: 2Gi
    storageClassName: do-block-storage
  config:
    defaultProvider: openai
    defaultModel: gpt-5.0-mini
    # The referenced Secret should expose OPENAI_API_KEY for the native OpenAI provider.
    envSecretRef:
      name: demo-user-provider-env
  exposure:
    httpRoute:
      enabled: false
      host: zeroclaw-dev.example.com
      path: /
      pathMatch: PathPrefix
      gatewayName: public-edge
      gatewayNamespace: envoy-gateway-system
      parentSectionName: https
