name: Test Workflow

on:
  workflow_call:
    inputs:
      registry:
        description: 'Docker registry URL'
        required: false
        default: 'registry.digitalocean.com/crawbl'
        type: string
    outputs:
      test-output:
        value: ${{ jobs.test.outputs.result }}
    secrets:
      test-secret:
        required: true

jobs:
  test:
    runs-on: ubuntu-24.04
    outputs:
      result: ${{ steps.echo.outputs.value }}
    steps:
      - name: Echo
        id: echo
        run: echo "value=test" >> $GITHUB_OUTPUT
